(()=>{
'use strict';
const {VERSION,AGES,PASS,$,buildQuiz,generateQuestion,validate}=window.QF;
let selectedAge=13,questions=[],position=0,selected=null,answers=[],lastSeed='',lastCount=10;
const ages=$('#ages');
for(const age of AGES){const button=document.createElement('button');button.className='age'+(age===selectedAge?' on':'');button.textContent=`${age} anni`;button.type='button';button.addEventListener('click',()=>{selectedAge=age;[...ages.children].forEach(x=>x.classList.remove('on'));button.classList.add('on')});ages.appendChild(button)}
function randomSeed(){return `${Date.now().toString(36)}-${crypto.getRandomValues(new Uint32Array(1))[0].toString(36)}`}
function start(reuse=false){const count=Number($('#count-select').value);let seed=reuse?lastSeed:$('#seed').value.trim();if(!seed)seed=randomSeed();lastSeed=seed;lastCount=count;$('#seed').value=seed;questions=buildQuiz(selectedAge,seed,count);position=0;selected=null;answers=[];$('#setup').classList.add('hide');$('#result').classList.add('hide');$('#game').classList.remove('hide');renderQuestion()}
function renderQuestion(){const q=questions[position];$('#counter').textContent=`Domanda ${position+1} di ${questions.length}`;$('#meta').textContent=`${selectedAge} anni · livello ${q.d}`;$('#bar').style.width=`${((position+1)/questions.length)*100}%`;$('#tags').textContent=`${q.cat} · famiglia ${q.f+1}/4`;$('#question').textContent=q.q;$('#answers').replaceChildren();selected=null;$('#next').disabled=true;for(const value of q.a){const button=document.createElement('button');button.className='ans';button.type='button';button.textContent=value;button.addEventListener('click',()=>{selected=value;[...$('#answers').children].forEach(x=>x.classList.remove('on'));button.classList.add('on');$('#next').disabled=false});$('#answers').appendChild(button)}$('#status').textContent=`Difficoltà ${q.d}/5`;$('#next').textContent=position===questions.length-1?'Risultato':'Prossima'}
function finish(){const correct=questions.filter((q,i)=>q.c===answers[i]).length;const score=Math.round(correct/questions.length*100);const win=score>=PASS;const recordKey=`quizforge:${VERSION}:record:${selectedAge}:${questions.length}`;const old=Number(localStorage.getItem(recordKey)||0);if(score>old)localStorage.setItem(recordKey,String(score));$('#game').classList.add('hide');$('#result').classList.remove('hide');$('#emoji').textContent=win?'🏆':'🧠';$('#result-title').textContent=win?'Sfida vinta!':'Continua l’allenamento!';$('#score').textContent=`${score}%`;$('#message').textContent=`${correct} corrette su ${questions.length}. ${score>old?'Nuovo record!':`Record: ${Math.max(old,score)}%.`}`;$('#stats').replaceChildren(stat(correct,'corrette'),stat(questions.length-correct,'sbagliate'),stat(`${Math.ceil(questions.length*PASS/100)}/${questions.length}`,'per vincere'));$('#challenge').textContent=`Codice sfida: ${lastSeed}`;const review=$('#review');review.replaceChildren();const heading=document.createElement('h3');heading.textContent='Ripasso';review.appendChild(heading);questions.forEach((q,i)=>{if(answers[i]===q.c)return;const article=document.createElement('article');const title=document.createElement('b');title.textContent=`${i+1}. ${q.q}`;const yours=document.createElement('p');yours.className='bad';yours.textContent=`La tua risposta: ${answers[i]}`;const right=document.createElement('p');right.className='ok';right.textContent=`Corretta: ${q.c}`;const explanation=document.createElement('p');explanation.className='muted';explanation.textContent=q.e;article.append(title,yours,right,explanation);review.appendChild(article)});if(correct===questions.length){const perfect=document.createElement('article');perfect.className='ok';perfect.textContent='Risultato perfetto: nessun errore.';review.appendChild(perfect)}}
function stat(value,label){const box=document.createElement('div');box.className='stat';const strong=document.createElement('b');strong.textContent=String(value);const br=document.createElement('br');const span=document.createElement('span');span.className='muted';span.textContent=label;box.append(strong,br,span);return box}
$('#start').addEventListener('click',()=>start(false));
$('#next').addEventListener('click',()=>{if(selected===null)return;answers.push(selected);if(position<questions.length-1){position++;renderQuestion()}else finish()});
$('#again').addEventListener('click',()=>{$('#result').classList.add('hide');$('#setup').classList.remove('hide');$('#seed').value=''});
$('#repeat').addEventListener('click',()=>{$('#count-select').value=String(lastCount);start(true)});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
window.QuizForge=Object.freeze({version:VERSION,buildQuiz,generateQuestion,validate});
})();
